spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phone?characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  com:
    example:
      demo: debug

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  # 配置 mybatis xml 的文件路径
  mapper-locations: classpath:mybatis/**Mapper.xml




