# 配置 mysql 驱动
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/onlinemusic?characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# 开启 mybatis sql 日志打印
logging:
  level:
    com:
      example:
        demo: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


private:
  key:
    url: f:/private.txt

public:
  key:
    url: f:/public.txt